spring.application.name=server

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=cinema-management-database;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto= update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nhomweb11@gmail.com
spring.mail.password=dsil ucwk hyon usoi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=AD4L9Ay9HTzQp8rKf2xNwV7bU6mYcR1sG4hJkP0a
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=6MB

cloudinary.enabled=true

CLOUDINARY_CLOUD_NAME=dwzvtnip3
CLOUDINARY_API_KEY=738942571993247
CLOUDINARY_API_SECRET=4-RooJDf3SrUTKS2yFPtbjJqxVI
